/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas.Cliente;

/**
 *
 * @author franco
 */
public class ClienteGestion extends javax.swing.JPanel {

    /**
     * Creates new form ClienteAgraga
     */
    public ClienteGestion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        JL_botonAgregar = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        JT_Apellido = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        JT_domicilio = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        JT_telefono = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        JT_estado = new javax.swing.JTextField();
        JT_nombre1 = new javax.swing.JTextField();
        JL_Eliminar = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 204, 255));
        setMinimumSize(new java.awt.Dimension(820, 530));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 231, -1, -1));

        jLabel17.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1486486316-arrow-film-movie-play-player-start-video_81236.png"))); // NOI18N
        jLabel17.setText("TODOS");
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 25, 130, 43));

        JL_botonAgregar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        JL_botonAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/business_application_addmale_useradd_insert_add_user_client_2312.png"))); // NOI18N
        JL_botonAgregar.setText("AGREGAR");
        JL_botonAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JL_botonAgregarMouseClicked(evt);
            }
        });
        add(JL_botonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 23, 143, 47));

        jLabel16.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel16.setText("NOMBRE:");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, 30));

        jLabel19.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel19.setText("APELLIDO:");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, 30));

        JT_Apellido.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        add(JT_Apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 320, -1));

        jLabel20.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel20.setText("DOMICILIO:");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, 30));

        JT_domicilio.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        add(JT_domicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 320, -1));

        jLabel21.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel21.setText("TELEFONO:");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, 30));

        JT_telefono.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        add(JT_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 320, -1));

        jLabel22.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel22.setText("ESTADO:");
        add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, 30));

        JT_estado.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        add(JT_estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 320, -1));

        JT_nombre1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        add(JT_nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 320, 30));

        JL_Eliminar.setBackground(new java.awt.Color(204, 204, 204));
        JL_Eliminar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        JL_Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/male-user-remove_25351.png"))); // NOI18N
        JL_Eliminar.setText("ELIMINAR");
        JL_Eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JL_EliminarMouseClicked(evt);
            }
        });
        add(JL_Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, -1, -1));

        jLabel26.setBackground(new java.awt.Color(204, 204, 204));
        jLabel26.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/businessapplication_edit_male_user_thepencil_theclient_negocio_2321_1.png"))); // NOI18N
        jLabel26.setText("MODIFICAR");
        add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 480, -1, -1));

        jLabel25.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/business_application_addmale_useradd_insert_add_user_client_2312.png"))); // NOI18N
        jLabel25.setText("AGREGAR");
        add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 480, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void JL_botonAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JL_botonAgregarMouseClicked
        //BOTON PARA MENU DE AGREGAR CLIENTE
        //JP_agregarPanel.setVisible(true);
        //JP_TodosLosClientesPanel.setVisible(false);
    }//GEN-LAST:event_JL_botonAgregarMouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        // TODO add your handling code here
        //JP_TodosLosClientesPanel.setVisible(true);
        //JP_agregarPanel.setVisible(false);
    }//GEN-LAST:event_jLabel17MouseClicked

    private void JL_EliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JL_EliminarMouseClicked
        // BOTON ELIMINAR DE CLIENTES
    }//GEN-LAST:event_JL_EliminarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JL_Eliminar;
    private javax.swing.JLabel JL_botonAgregar;
    private javax.swing.JTextField JT_Apellido;
    private javax.swing.JTextField JT_domicilio;
    private javax.swing.JTextField JT_estado;
    private javax.swing.JTextField JT_nombre1;
    private javax.swing.JTextField JT_telefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    // End of variables declaration//GEN-END:variables
}
