/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author VILLORD
 */
public class Menu extends javax.swing.JFrame {

    
    public Menu() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JP_Menu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JP_inicio = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        JP_productos = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        JP_ventas = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        JP_empleados = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        JP_clientes = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        JP_salir = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        JP_panelInicial = new javax.swing.JPanel();
        JP_Home = new javax.swing.JPanel();
        JP_panelClientes = new javax.swing.JPanel();
        JP_panelEmpleados = new javax.swing.JPanel();
        JP_panelVentas = new javax.swing.JPanel();
        JP_panelProductos = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JP_Menu.setBackground(new java.awt.Color(112, 155, 255));
        JP_Menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/3135715.png"))); // NOI18N
        JP_Menu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, -1, -1));

        JP_inicio.setBackground(new java.awt.Color(120, 110, 255));
        JP_inicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JP_inicioMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("INICIO");

        javax.swing.GroupLayout JP_inicioLayout = new javax.swing.GroupLayout(JP_inicio);
        JP_inicio.setLayout(JP_inicioLayout);
        JP_inicioLayout.setHorizontalGroup(
            JP_inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_inicioLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel3)
                .addContainerGap(134, Short.MAX_VALUE))
        );
        JP_inicioLayout.setVerticalGroup(
            JP_inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_inicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        JP_Menu.add(JP_inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 201, 266, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        JP_Menu.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 177, 254, 12));

        JP_productos.setBackground(new java.awt.Color(120, 110, 255));
        JP_productos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JP_productosMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PRODUCTOS");

        javax.swing.GroupLayout JP_productosLayout = new javax.swing.GroupLayout(JP_productos);
        JP_productos.setLayout(JP_productosLayout);
        JP_productosLayout.setHorizontalGroup(
            JP_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_productosLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel7)
                .addContainerGap(76, Short.MAX_VALUE))
        );
        JP_productosLayout.setVerticalGroup(
            JP_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP_productosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        JP_Menu.add(JP_productos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 355, 266, -1));

        JP_ventas.setBackground(new java.awt.Color(120, 110, 255));
        JP_ventas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JP_ventasMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("VENTAS");

        javax.swing.GroupLayout JP_ventasLayout = new javax.swing.GroupLayout(JP_ventas);
        JP_ventas.setLayout(JP_ventasLayout);
        JP_ventasLayout.setHorizontalGroup(
            JP_ventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_ventasLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );
        JP_ventasLayout.setVerticalGroup(
            JP_ventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP_ventasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JP_Menu.add(JP_ventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 321, 266, -1));

        JP_empleados.setBackground(new java.awt.Color(120, 110, 255));
        JP_empleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JP_empleadosMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("EMPLEADOS");

        javax.swing.GroupLayout JP_empleadosLayout = new javax.swing.GroupLayout(JP_empleados);
        JP_empleados.setLayout(JP_empleadosLayout);
        JP_empleadosLayout.setHorizontalGroup(
            JP_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_empleadosLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel6)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        JP_empleadosLayout.setVerticalGroup(
            JP_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP_empleadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        JP_Menu.add(JP_empleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 281, -1, -1));

        JP_clientes.setBackground(new java.awt.Color(120, 110, 255));
        JP_clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JP_clientesMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CLIENTES");

        javax.swing.GroupLayout JP_clientesLayout = new javax.swing.GroupLayout(JP_clientes);
        JP_clientes.setLayout(JP_clientesLayout);
        JP_clientesLayout.setHorizontalGroup(
            JP_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_clientesLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel4)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        JP_clientesLayout.setVerticalGroup(
            JP_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_clientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        JP_Menu.add(JP_clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 241, 266, -1));

        jPanel1.setBackground(new java.awt.Color(112, 155, 255));

        jLabel8.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("PERFIL");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        JP_Menu.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 6, -1, -1));

        JP_salir.setBackground(new java.awt.Color(120, 110, 255));
        JP_salir.setForeground(new java.awt.Color(255, 255, 255));
        JP_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JP_salirMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Roboto Medium", 2, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("SALIR");

        javax.swing.GroupLayout JP_salirLayout = new javax.swing.GroupLayout(JP_salir);
        JP_salir.setLayout(JP_salirLayout);
        JP_salirLayout.setHorizontalGroup(
            JP_salirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_salirLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );
        JP_salirLayout.setVerticalGroup(
            JP_salirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        JP_Menu.add(JP_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 431, 266, -1));

        getContentPane().add(JP_Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 530));

        JP_panelInicial.setBackground(new java.awt.Color(255, 255, 255));
        JP_panelInicial.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JP_Home.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout JP_HomeLayout = new javax.swing.GroupLayout(JP_Home);
        JP_Home.setLayout(JP_HomeLayout);
        JP_HomeLayout.setHorizontalGroup(
            JP_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );
        JP_HomeLayout.setVerticalGroup(
            JP_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );

        JP_panelInicial.add(JP_Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 530));

        JP_panelClientes.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout JP_panelClientesLayout = new javax.swing.GroupLayout(JP_panelClientes);
        JP_panelClientes.setLayout(JP_panelClientesLayout);
        JP_panelClientesLayout.setHorizontalGroup(
            JP_panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );
        JP_panelClientesLayout.setVerticalGroup(
            JP_panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );

        JP_panelInicial.add(JP_panelClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        JP_panelEmpleados.setBackground(new java.awt.Color(51, 153, 255));

        javax.swing.GroupLayout JP_panelEmpleadosLayout = new javax.swing.GroupLayout(JP_panelEmpleados);
        JP_panelEmpleados.setLayout(JP_panelEmpleadosLayout);
        JP_panelEmpleadosLayout.setHorizontalGroup(
            JP_panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );
        JP_panelEmpleadosLayout.setVerticalGroup(
            JP_panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );

        JP_panelInicial.add(JP_panelEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        JP_panelVentas.setBackground(new java.awt.Color(0, 51, 255));

        javax.swing.GroupLayout JP_panelVentasLayout = new javax.swing.GroupLayout(JP_panelVentas);
        JP_panelVentas.setLayout(JP_panelVentasLayout);
        JP_panelVentasLayout.setHorizontalGroup(
            JP_panelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );
        JP_panelVentasLayout.setVerticalGroup(
            JP_panelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );

        JP_panelInicial.add(JP_panelVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        JP_panelProductos.setBackground(new java.awt.Color(0, 0, 153));

        javax.swing.GroupLayout JP_panelProductosLayout = new javax.swing.GroupLayout(JP_panelProductos);
        JP_panelProductos.setLayout(JP_panelProductosLayout);
        JP_panelProductosLayout.setHorizontalGroup(
            JP_panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );
        JP_panelProductosLayout.setVerticalGroup(
            JP_panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );

        JP_panelInicial.add(JP_panelProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(JP_panelInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 0, 790, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JP_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JP_salirMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_JP_salirMouseClicked

    private void JP_inicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JP_inicioMouseClicked
        // VENTANA DE INICIO
        JP_Home.setVisible(true);
        JP_panelClientes.setVisible(false);
        JP_panelEmpleados.setVisible(false);
        JP_panelVentas.setVisible(false);
        JP_panelProductos.setVisible(false);
        
    }//GEN-LAST:event_JP_inicioMouseClicked

    private void JP_clientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JP_clientesMouseClicked
        // VENTANA DE CLIENTES
        
        JP_panelClientes.setVisible(true);
        JP_Home.setVisible(false);
        JP_panelEmpleados.setVisible(false);
        JP_panelVentas.setVisible(false);
        JP_panelProductos.setVisible(false);
    }//GEN-LAST:event_JP_clientesMouseClicked

    private void JP_empleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JP_empleadosMouseClicked
        // VENTANA DE EMPLEADOS
        
        JP_panelEmpleados.setVisible(true);
        JP_Home.setVisible(false);
        JP_panelClientes.setVisible(false);
        JP_panelVentas.setVisible(false);
        JP_panelProductos.setVisible(false);
    }//GEN-LAST:event_JP_empleadosMouseClicked

    private void JP_ventasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JP_ventasMouseClicked
        // VENTANA DE VENTAS
        
        JP_panelVentas.setVisible(true);
        JP_Home.setVisible(false);
        JP_panelClientes.setVisible(false);
        JP_panelEmpleados.setVisible(false);
        JP_panelProductos.setVisible(false);
    }//GEN-LAST:event_JP_ventasMouseClicked

    private void JP_productosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JP_productosMouseClicked
        // VENTANA DE PRODUCTOS
        
        JP_panelProductos.setVisible(true);
        JP_Home.setVisible(false);
        JP_panelClientes.setVisible(false);
        JP_panelEmpleados.setVisible(false);
        JP_panelVentas.setVisible(false);
        
    }//GEN-LAST:event_JP_productosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JP_Home;
    private javax.swing.JPanel JP_Menu;
    private javax.swing.JPanel JP_clientes;
    private javax.swing.JPanel JP_empleados;
    private javax.swing.JPanel JP_inicio;
    private javax.swing.JPanel JP_panelClientes;
    private javax.swing.JPanel JP_panelEmpleados;
    private javax.swing.JPanel JP_panelInicial;
    private javax.swing.JPanel JP_panelProductos;
    private javax.swing.JPanel JP_panelVentas;
    private javax.swing.JPanel JP_productos;
    private javax.swing.JPanel JP_salir;
    private javax.swing.JPanel JP_ventas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
